// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:36bfb0d6-bbbc-4572-b8b6-54eed97c806d",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "1d84e8c05329424bb517be82283289f7",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "amplifyjsplayground-20181113114341--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifyjsplayground-20181113114341--hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
